title: 
  present: Enter a title for this horse!
price:
  present: Enter a price for this horse!
  int: Please use a number without a decimal!
description:
  present: Enter a description about this horse!
gender:
  present: Select the gender of this horse!
age:
  present: Select the age of this horse!
temp:
  present: Select the temperament of this horse!
state:
  present: Select the state where you currently live!
zip:
  present: Enter your current five digit zip code!
  length: Enter your current five digit zip code!
email:
  present: Enter an email to contact you!
  email: Enter a valid email address!

